### ISSUE TITLE
Module 2, Week 1, peer to peer code review

### ISSUE THREAD

**Issue by Mahamadou-Nouridine** [ShaliniNayan/Awesome-Books#1]
You've done good work so far, but your code still requires some changes:

- The books are not being displayed because of incompatibility of the element Id in the HTML document;
- Same thing for the elements of the input, kindly change 'title-input' id to 'title' and 'author-input' to 'author' respectively at the line 44 and 45 so you can use the values to create a new book

**Comment by ShaliniNayan** [comment]
Thanks & Noted
